-- 0007_seed_exercises_expanded.sql
-- GENERATED by scripts/build_exercise_seed.py from
-- free-exercise-db (github.com/yuhonas/free-exercise-db,
-- public domain / Unlicense). Raw dump + images are a
-- one-time generation input and are NOT committed.
--
-- Curation: foundational compound lifts + commonly-
-- programmed accessories across ALL major muscle groups
-- (quads/hams/glutes/chest/back/shoulders/traps/biceps/
-- triceps/calves/core/forearms) and ALL modalities
-- (barbell/dumbbell/machine/cable->machine/bw incl. the
-- bodyweight staples push-up, plank, dips, BW squat/lunge,
-- chin-up, inverted row, hanging leg raise) and the
-- barbell glute bridge (barbell).
-- Excluded: near-duplicate grip/stance/Smith variants,
-- behind-the-neck, novelty/circus, band/ball/foam-only,
-- kettlebell flows, stretching/cardio/plyo-only.
--
-- STRICTLY ADDITIVE + IDEMPOTENT. 0007 inserts ONLY the
-- net-new exercises -- ids NOT already seeded by ANY earlier
-- migration. It does NOT restate the original 12 (0002) nor
-- the 5 timed core/hold exercises (0004: ex_plank,
-- ex_side_plank, ex_hollow, ex_dead_hang, ex_wall_sit) --
-- those rows are owned + frozen by their own migrations and
-- keep their original definitions (e.g. plank stays
-- modality='timed'/unit='sec'). Zero id overlap with
-- 0002/0004. INSERT OR IGNORE on the UUID PK keeps re-runs
-- a no-op. created_at = 0 (epoch): seed rows are timeless.
--
-- Plus ONE idempotent UPDATE: appends the conventional
-- alias "dumbbell press" to the EXISTING 0002 row
-- ex_db_press (Dumbbell Bench Press) so that phrase resolves
-- to the bench press, not the new dumbbell shoulder press.
-- Additive (alias-only mutation, no row add/delete) and
-- idempotent (writes the identical literal each run).
INSERT OR IGNORE INTO exercises
  (id, name, primary_muscle, secondary_muscles, modality, unit, aliases, created_at)
VALUES
  ('ex_goblet_squat', 'Goblet Squat', 'quads', '["calves", "glutes", "hamstrings", "shoulders"]', 'dumbbell', 'lb', '["goblet squat", "goblet"]', 0),
  ('ex_db_squat', 'Dumbbell Squat', 'quads', '["calves", "glutes", "hamstrings", "back"]', 'dumbbell', 'lb', '["dumbbell squat"]', 0),
  ('ex_hack_squat', 'Hack Squat', 'quads', '["calves", "glutes", "hamstrings"]', 'machine', 'lb', '["hack squat"]', 0),
  ('ex_bw_squat', 'Bodyweight Squat', 'quads', '["glutes", "hamstrings"]', 'bw', 'lb', '["bodyweight squat", "air squat"]', 0),
  ('ex_box_squat', 'Box Squat', 'quads', '["calves", "glutes", "hamstrings", "back"]', 'barbell', 'lb', '["box squat"]', 0),
  ('ex_ohs', 'Overhead Squat', 'quads', '["core", "calves", "glutes", "hamstrings", "back", "shoulders", "triceps"]', 'barbell', 'lb', '["overhead squat", "ohs"]', 0),
  ('ex_bb_lunge', 'Barbell Lunge', 'quads', '["calves", "glutes", "hamstrings"]', 'barbell', 'lb', '["barbell lunge"]', 0),
  ('ex_db_lunge', 'Dumbbell Lunge', 'quads', '["calves", "glutes", "hamstrings"]', 'dumbbell', 'lb', '["dumbbell lunge", "db lunge"]', 0),
  ('ex_bw_lunge', 'Bodyweight Walking Lunge', 'quads', '["calves", "glutes", "hamstrings"]', 'bw', 'lb', '["bodyweight walking lunge", "walking lunge", "bodyweight lunge"]', 0),
  ('ex_bb_walking_lunge', 'Barbell Walking Lunge', 'quads', '["calves", "glutes", "hamstrings"]', 'barbell', 'lb', '["barbell walking lunge"]', 0),
  ('ex_db_reverse_lunge', 'Dumbbell Reverse Lunge', 'quads', '["calves", "glutes", "hamstrings"]', 'dumbbell', 'lb', '["dumbbell reverse lunge", "reverse lunge", "db reverse lunge"]', 0),
  ('ex_db_split_squat', 'Dumbbell Bulgarian Split Squat', 'quads', '["glutes", "hamstrings"]', 'dumbbell', 'lb', '["dumbbell bulgarian split squat", "bulgarian split squat", "split squat", "rfess"]', 0),
  ('ex_db_step_up', 'Dumbbell Step-Up', 'quads', '["calves", "glutes", "hamstrings"]', 'dumbbell', 'lb', '["dumbbell step-up", "step up", "step-up", "db step up"]', 0),
  ('ex_bb_step_up', 'Barbell Step-Up', 'quads', '["calves", "glutes", "hamstrings"]', 'barbell', 'lb', '["barbell step-up", "barbell step up"]', 0),
  ('ex_leg_extension', 'Leg Extension', 'quads', '[]', 'machine', 'lb', '["leg extension", "leg extensions", "quad extension"]', 0),
  ('ex_lying_leg_curl', 'Lying Leg Curl', 'hamstrings', '[]', 'machine', 'lb', '["lying leg curl", "leg curl", "hamstring curl"]', 0),
  ('ex_seated_leg_curl', 'Seated Leg Curl', 'hamstrings', '[]', 'machine', 'lb', '["seated leg curl"]', 0),
  ('ex_standing_leg_curl', 'Standing Leg Curl', 'hamstrings', '[]', 'machine', 'lb', '["standing leg curl"]', 0),
  ('ex_stiff_leg_dl', 'Stiff-Legged Deadlift', 'hamstrings', '["glutes", "back"]', 'barbell', 'lb', '["stiff-legged deadlift", "stiff leg deadlift", "sldl", "stiff legged deadlift"]', 0),
  ('ex_db_rdl', 'Dumbbell Romanian Deadlift', 'hamstrings', '["glutes", "back"]', 'dumbbell', 'lb', '["dumbbell romanian deadlift", "dumbbell rdl", "db rdl"]', 0),
  ('ex_sumo_dl', 'Sumo Deadlift', 'hamstrings', '["forearms", "glutes", "back", "quads", "traps"]', 'barbell', 'lb', '["sumo deadlift", "sumo dl"]', 0),
  ('ex_good_morning', 'Good Morning', 'hamstrings', '["core", "glutes", "back"]', 'barbell', 'lb', '["good morning", "good mornings"]', 0),
  ('ex_ghr', 'Glute Ham Raise', 'hamstrings', '["calves", "glutes"]', 'machine', 'lb', '["glute ham raise", "ghr", "glute-ham raise"]', 0),
  ('ex_rack_pull', 'Rack Pull', 'back', '["forearms", "glutes", "hamstrings", "traps"]', 'barbell', 'lb', '["rack pull", "rack pulls"]', 0),
  ('ex_deficit_dl', 'Deficit Deadlift', 'back', '["forearms", "glutes", "hamstrings", "quads", "traps"]', 'barbell', 'lb', '["deficit deadlift"]', 0),
  ('ex_hip_thrust', 'Hip Thrust', 'glutes', '["calves", "hamstrings"]', 'barbell', 'lb', '["hip thrust", "hip thrusts"]', 0),
  ('ex_glute_bridge', 'Glute Bridge', 'glutes', '["calves", "hamstrings"]', 'barbell', 'lb', '["glute bridge"]', 0),
  ('ex_sl_glute_bridge', 'Single-Leg Glute Bridge', 'glutes', '["hamstrings"]', 'bw', 'lb', '["single-leg glute bridge", "single leg glute bridge"]', 0),
  ('ex_glute_kickback', 'Glute Kickback', 'glutes', '["hamstrings"]', 'bw', 'lb', '["glute kickback", "donkey kick"]', 0),
  ('ex_cable_kickback', 'Cable Glute Kickback', 'glutes', '["hamstrings"]', 'machine', 'lb', '["cable glute kickback", "cable kickback"]', 0),
  ('ex_pull_through', 'Cable Pull-Through', 'glutes', '["hamstrings", "back"]', 'machine', 'lb', '["cable pull-through", "pull through", "cable pull through"]', 0),
  ('ex_standing_calf_raise', 'Standing Calf Raise', 'calves', '[]', 'machine', 'lb', '["standing calf raise", "calf raise", "calf raises"]', 0),
  ('ex_seated_calf_raise', 'Seated Calf Raise', 'calves', '[]', 'machine', 'lb', '["seated calf raise"]', 0),
  ('ex_calf_press', 'Calf Press', 'calves', '[]', 'machine', 'lb', '["calf press"]', 0),
  ('ex_db_calf_raise', 'Dumbbell Calf Raise', 'calves', '[]', 'dumbbell', 'lb', '["dumbbell calf raise"]', 0),
  ('ex_bb_calf_raise', 'Barbell Calf Raise', 'calves', '[]', 'barbell', 'lb', '["barbell calf raise"]', 0),
  ('ex_decline_bench', 'Decline Barbell Bench Press', 'chest', '["shoulders", "triceps"]', 'barbell', 'lb', '["decline barbell bench press", "decline bench", "decline bench press"]', 0),
  ('ex_incline_db_press', 'Incline Dumbbell Press', 'chest', '["shoulders", "triceps"]', 'dumbbell', 'lb', '["incline dumbbell press", "incline db press", "incline db bench"]', 0),
  ('ex_decline_db_press', 'Decline Dumbbell Bench Press', 'chest', '["shoulders", "triceps"]', 'dumbbell', 'lb', '["decline dumbbell bench press", "decline dumbbell press", "decline db bench"]', 0),
  ('ex_db_fly', 'Dumbbell Fly', 'chest', '[]', 'dumbbell', 'lb', '["dumbbell fly", "db fly", "dumbbell flyes", "chest fly"]', 0),
  ('ex_incline_db_fly', 'Incline Dumbbell Fly', 'chest', '["shoulders"]', 'dumbbell', 'lb', '["incline dumbbell fly", "incline db fly"]', 0),
  ('ex_cable_crossover', 'Cable Crossover', 'chest', '["shoulders"]', 'machine', 'lb', '["cable crossover", "cable crossovers"]', 0),
  ('ex_low_cable_crossover', 'Low Cable Crossover', 'chest', '["shoulders"]', 'machine', 'lb', '["low cable crossover"]', 0),
  ('ex_machine_chest_press', 'Machine Chest Press', 'chest', '["shoulders", "triceps"]', 'machine', 'lb', '["machine chest press", "machine bench press", "chest press"]', 0),
  ('ex_machine_incline_press', 'Machine Incline Press', 'chest', '["shoulders", "triceps"]', 'machine', 'lb', '["machine incline press"]', 0),
  ('ex_pushup', 'Push-Up', 'chest', '["shoulders", "triceps"]', 'bw', 'lb', '["push-up", "pushup", "push up", "press up", "press-up"]', 0),
  ('ex_incline_pushup', 'Incline Push-Up', 'chest', '["shoulders", "triceps"]', 'bw', 'lb', '["incline push-up", "incline pushup", "incline push up"]', 0),
  ('ex_decline_pushup', 'Decline Push-Up', 'chest', '["shoulders", "triceps"]', 'bw', 'lb', '["decline push-up", "decline pushup", "decline push up"]', 0),
  ('ex_feet_elevated_pushup', 'Feet-Elevated Push-Up', 'chest', '["shoulders", "triceps"]', 'bw', 'lb', '["feet-elevated push-up", "feet elevated pushup"]', 0),
  ('ex_db_pullover', 'Dumbbell Pullover', 'chest', '["back", "shoulders", "triceps"]', 'dumbbell', 'lb', '["dumbbell pullover", "db pullover", "pullover"]', 0),
  ('ex_db_row_two', 'Two-Arm Dumbbell Row', 'back', '["biceps", "shoulders"]', 'dumbbell', 'lb', '["two-arm dumbbell row", "two arm dumbbell row", "bent over dumbbell row"]', 0),
  ('ex_one_arm_db_row', 'One-Arm Dumbbell Row', 'back', '["biceps", "shoulders"]', 'dumbbell', 'lb', '["one-arm dumbbell row", "one arm dumbbell row", "single arm row", "db row", "dumbbell row"]', 0),
  ('ex_seated_cable_row', 'Seated Cable Row', 'back', '["biceps", "shoulders"]', 'machine', 'lb', '["seated cable row", "cable row", "seated row"]', 0),
  ('ex_tbar_row', 'T-Bar Row', 'back', '["biceps"]', 'barbell', 'lb', '["t-bar row", "t bar row", "tbar row"]', 0),
  ('ex_inverted_row', 'Inverted Row', 'back', '[]', 'bw', 'lb', '["inverted row", "bodyweight row", "australian pullup"]', 0),
  ('ex_wide_pulldown', 'Wide-Grip Lat Pulldown', 'back', '["biceps", "shoulders"]', 'machine', 'lb', '["wide-grip lat pulldown", "wide grip pulldown", "wide pulldown"]', 0),
  ('ex_close_pulldown', 'Close-Grip Lat Pulldown', 'back', '["biceps", "shoulders"]', 'machine', 'lb', '["close-grip lat pulldown", "close grip pulldown", "close pulldown"]', 0),
  ('ex_straight_arm_pulldown', 'Straight-Arm Pulldown', 'back', '[]', 'machine', 'lb', '["straight-arm pulldown", "straight arm pulldown"]', 0),
  ('ex_chinup', 'Chin-Up', 'back', '["biceps", "forearms"]', 'bw', 'lb', '["chin-up", "chinup", "underhand pullup"]', 0),
  ('ex_neutral_pullup', 'Neutral-Grip Pull-Up', 'back', '["biceps", "shoulders"]', 'bw', 'lb', '["neutral-grip pull-up", "neutral grip pullup", "v-bar pullup", "neutral pullup"]', 0),
  ('ex_reverse_grip_row', 'Reverse-Grip Barbell Row', 'back', '["biceps", "shoulders"]', 'barbell', 'lb', '["reverse-grip barbell row", "reverse grip row", "underhand row", "yates row"]', 0),
  ('ex_smith_row', 'Smith Machine Row', 'back', '["biceps", "shoulders"]', 'machine', 'lb', '["smith machine row", "smith row"]', 0),
  ('ex_bb_shrug', 'Barbell Shrug', 'traps', '[]', 'barbell', 'lb', '["barbell shrug", "shrug", "shrugs"]', 0),
  ('ex_db_shrug', 'Dumbbell Shrug', 'traps', '[]', 'dumbbell', 'lb', '["dumbbell shrug", "db shrug"]', 0),
  ('ex_cable_shrug', 'Cable Shrug', 'traps', '[]', 'machine', 'lb', '["cable shrug"]', 0),
  ('ex_upright_row', 'Upright Row', 'shoulders', '["traps"]', 'barbell', 'lb', '["upright row", "barbell upright row"]', 0),
  ('ex_face_pull', 'Face Pull', 'shoulders', '["back"]', 'machine', 'lb', '["face pull", "face pulls"]', 0),
  ('ex_db_ohp', 'Dumbbell Shoulder Press', 'shoulders', '["triceps"]', 'dumbbell', 'lb', '["dumbbell shoulder press", "db shoulder press", "db ohp"]', 0),
  ('ex_seated_db_press', 'Seated Dumbbell Press', 'shoulders', '["triceps"]', 'dumbbell', 'lb', '["seated dumbbell press", "seated db press"]', 0),
  ('ex_arnold_press', 'Arnold Press', 'shoulders', '["triceps"]', 'dumbbell', 'lb', '["arnold press", "arnold"]', 0),
  ('ex_push_press', 'Push Press', 'shoulders', '["quads", "triceps"]', 'barbell', 'lb', '["push press"]', 0),
  ('ex_lateral_raise', 'Dumbbell Lateral Raise', 'shoulders', '[]', 'dumbbell', 'lb', '["dumbbell lateral raise", "lateral raise", "side lateral raise", "lat raise", "side raise"]', 0),
  ('ex_cable_lateral_raise', 'Cable Lateral Raise', 'shoulders', '["back", "traps"]', 'machine', 'lb', '["cable lateral raise"]', 0),
  ('ex_front_raise', 'Dumbbell Front Raise', 'shoulders', '[]', 'dumbbell', 'lb', '["dumbbell front raise", "front raise", "front raises"]', 0),
  ('ex_reverse_fly', 'Dumbbell Reverse Fly', 'shoulders', '[]', 'dumbbell', 'lb', '["dumbbell reverse fly", "reverse fly", "rear delt fly", "reverse flyes", "rear delt flye"]', 0),
  ('ex_machine_reverse_fly', 'Machine Reverse Fly', 'shoulders', '[]', 'machine', 'lb', '["machine reverse fly", "reverse pec deck"]', 0),
  ('ex_machine_shoulder_press', 'Machine Shoulder Press', 'shoulders', '["triceps"]', 'machine', 'lb', '["machine shoulder press"]', 0),
  ('ex_cable_rear_delt_fly', 'Cable Rear Delt Fly', 'shoulders', '[]', 'machine', 'lb', '["cable rear delt fly"]', 0),
  ('ex_hspu', 'Handstand Push-Up', 'shoulders', '["triceps"]', 'bw', 'lb', '["handstand push-up", "handstand pushup", "hspu", "handstand push up"]', 0),
  ('ex_seated_bb_press', 'Seated Barbell Press', 'shoulders', '["triceps"]', 'barbell', 'lb', '["seated barbell press", "seated military press"]', 0),
  ('ex_bb_curl', 'Barbell Curl', 'biceps', '["forearms"]', 'barbell', 'lb', '["barbell curl", "bb curl", "bicep curl", "biceps curl"]', 0),
  ('ex_db_curl', 'Dumbbell Curl', 'biceps', '["forearms"]', 'dumbbell', 'lb', '["dumbbell curl", "db curl", "dumbbell bicep curl"]', 0),
  ('ex_hammer_curl', 'Hammer Curl', 'biceps', '[]', 'dumbbell', 'lb', '["hammer curl", "hammer curls", "hammers"]', 0),
  ('ex_incline_db_curl', 'Incline Dumbbell Curl', 'biceps', '[]', 'dumbbell', 'lb', '["incline dumbbell curl", "incline curl", "incline db curl"]', 0),
  ('ex_preacher_curl', 'Preacher Curl', 'biceps', '[]', 'barbell', 'lb', '["preacher curl", "preacher curls"]', 0),
  ('ex_concentration_curl', 'Concentration Curl', 'biceps', '["forearms"]', 'dumbbell', 'lb', '["concentration curl", "concentration curls"]', 0),
  ('ex_ez_curl', 'EZ-Bar Curl', 'biceps', '[]', 'barbell', 'lb', '["ez-bar curl", "ez bar curl", "ez curl"]', 0),
  ('ex_cable_curl', 'Cable Curl', 'biceps', '[]', 'machine', 'lb', '["cable curl", "cable bicep curl"]', 0),
  ('ex_spider_curl', 'Spider Curl', 'biceps', '[]', 'barbell', 'lb', '["spider curl", "spider curls"]', 0),
  ('ex_reverse_curl', 'Reverse Curl', 'biceps', '["forearms"]', 'barbell', 'lb', '["reverse curl", "reverse barbell curl"]', 0),
  ('ex_tricep_pushdown', 'Triceps Pushdown', 'triceps', '[]', 'machine', 'lb', '["triceps pushdown", "tricep pushdown", "pushdown", "tricep pressdown"]', 0),
  ('ex_rope_pushdown', 'Rope Triceps Pushdown', 'triceps', '[]', 'machine', 'lb', '["rope triceps pushdown", "rope pushdown", "rope tricep pushdown"]', 0),
  ('ex_cgbp', 'Close-Grip Bench Press', 'triceps', '["chest", "shoulders"]', 'barbell', 'lb', '["close-grip bench press", "close grip bench", "cgbp"]', 0),
  ('ex_skullcrusher', 'Skullcrusher', 'triceps', '["forearms"]', 'barbell', 'lb', '["skullcrusher", "skull crusher", "lying tricep extension"]', 0),
  ('ex_dips', 'Dips', 'triceps', '["chest", "shoulders"]', 'bw', 'lb', '["dips", "dip", "tricep dip", "tricep dips", "chest dip", "parallel bar dip"]', 0),
  ('ex_bench_dips', 'Bench Dip', 'triceps', '["chest", "shoulders"]', 'bw', 'lb', '["bench dip", "bench dips"]', 0),
  ('ex_overhead_tricep_ext', 'Cable Overhead Triceps Extension', 'triceps', '[]', 'machine', 'lb', '["cable overhead triceps extension", "overhead tricep extension", "overhead triceps extension", "tricep extension"]', 0),
  ('ex_db_overhead_ext', 'Dumbbell Overhead Triceps Extension', 'triceps', '[]', 'dumbbell', 'lb', '["dumbbell overhead triceps extension", "dumbbell overhead extension", "db tricep extension"]', 0),
  ('ex_tricep_kickback', 'Triceps Kickback', 'triceps', '[]', 'dumbbell', 'lb', '["triceps kickback", "tricep kickback", "kickback"]', 0),
  ('ex_machine_tricep_ext', 'Machine Triceps Extension', 'triceps', '[]', 'machine', 'lb', '["machine triceps extension", "machine tricep extension"]', 0),
  ('ex_machine_dip', 'Machine Dip', 'triceps', '["chest", "shoulders"]', 'machine', 'lb', '["machine dip", "assisted dip"]', 0),
  ('ex_hanging_leg_raise', 'Hanging Leg Raise', 'core', '[]', 'bw', 'lb', '["hanging leg raise", "hanging leg raises", "leg raise"]', 0),
  ('ex_cable_crunch', 'Cable Crunch', 'core', '[]', 'machine', 'lb', '["cable crunch", "cable crunches"]', 0),
  ('ex_crunch', 'Crunch', 'core', '[]', 'bw', 'lb', '["crunch", "crunches"]', 0),
  ('ex_situp', 'Sit-Up', 'core', '[]', 'bw', 'lb', '["sit-up", "situp", "sit up", "situps"]', 0),
  ('ex_russian_twist', 'Russian Twist', 'core', '["back"]', 'bw', 'lb', '["russian twist", "russian twists"]', 0),
  ('ex_reverse_crunch', 'Reverse Crunch', 'core', '[]', 'bw', 'lb', '["reverse crunch", "reverse crunches"]', 0),
  ('ex_pallof_press', 'Pallof Press', 'core', '["chest", "shoulders", "triceps"]', 'machine', 'lb', '["pallof press", "pallof"]', 0),
  ('ex_woodchop', 'Cable Woodchop', 'core', '["shoulders"]', 'machine', 'lb', '["cable woodchop", "woodchop", "wood chop"]', 0),
  ('ex_dead_bug', 'Dead Bug', 'core', '[]', 'bw', 'lb', '["dead bug", "deadbug"]', 0),
  ('ex_wrist_curl', 'Barbell Wrist Curl', 'forearms', '[]', 'barbell', 'lb', '["barbell wrist curl", "wrist curl", "wrist curls"]', 0),
  ('ex_reverse_wrist_curl', 'Barbell Reverse Wrist Curl', 'forearms', '[]', 'barbell', 'lb', '["barbell reverse wrist curl", "reverse wrist curl", "wrist extension"]', 0),
  ('ex_ab_wheel', 'Ab Wheel Rollout', 'core', '["shoulders","back"]', 'bw', 'lb', '["ab wheel rollout", "ab wheel", "ab rollout", "ab roller"]', 0),
  ('ex_sissy_squat', 'Sissy Squat', 'quads', '[]', 'bw', 'lb', '["sissy squat"]', 0);

-- Conventional-alias backfill for the existing 0002 row.
-- Idempotent: sets the exact target literal regardless of
-- current value, so re-running is a no-op.
UPDATE exercises SET aliases = '["db press", "dumbbell bench", "db bench", "dumbbell press"]' WHERE id = 'ex_db_press';
