-- 0020_exercise_demo_slugs.sql
-- GENERATED by scripts/build_demo_backfill.py from
-- free-exercise-db (github.com/yuhonas/free-exercise-db,
-- public domain / Unlicense).
--
-- Adds `demo_slug` to exercises and backfills every existing row
-- (0002 + 0004 + 0007 + 0009) that has a corresponding upstream
-- entry. The slug is the upstream `id` field (e.g. 'Barbell_Squat'),
-- which iOS uses as a key into either the bundled asset catalog
-- (foundational lifts) or the Worker-fronted R2 bucket (long tail).
-- Nullable on purpose: rows without an upstream pairing (planks,
-- holds, bird-dog, banded primitives) stay NULL — the demo sheet
-- renders cue text only. Backfilled here: 127 / 136 ex_* rows.
--
-- STRICTLY ADDITIVE: one ALTER + per-row UPDATEs. Re-running the
-- UPDATEs is idempotent (writes the same literal each time).

ALTER TABLE exercises ADD COLUMN demo_slug TEXT;

UPDATE exercises SET demo_slug = 'Arnold_Dumbbell_Press' WHERE id = 'ex_arnold_press';
UPDATE exercises SET demo_slug = 'Barbell_Squat' WHERE id = 'ex_back_squat';
UPDATE exercises SET demo_slug = 'Bent_Over_Barbell_Row' WHERE id = 'ex_barbell_row';
UPDATE exercises SET demo_slug = 'Standing_Barbell_Calf_Raise' WHERE id = 'ex_bb_calf_raise';
UPDATE exercises SET demo_slug = 'Barbell_Curl' WHERE id = 'ex_bb_curl';
UPDATE exercises SET demo_slug = 'Barbell_Lunge' WHERE id = 'ex_bb_lunge';
UPDATE exercises SET demo_slug = 'Barbell_Shrug' WHERE id = 'ex_bb_shrug';
UPDATE exercises SET demo_slug = 'Barbell_Step_Ups' WHERE id = 'ex_bb_step_up';
UPDATE exercises SET demo_slug = 'Barbell_Walking_Lunge' WHERE id = 'ex_bb_walking_lunge';
UPDATE exercises SET demo_slug = 'Barbell_Bench_Press_-_Medium_Grip' WHERE id = 'ex_bench';
UPDATE exercises SET demo_slug = 'Bench_Dips' WHERE id = 'ex_bench_dips';
UPDATE exercises SET demo_slug = 'Box_Squat' WHERE id = 'ex_box_squat';
UPDATE exercises SET demo_slug = 'Bodyweight_Walking_Lunge' WHERE id = 'ex_bw_lunge';
UPDATE exercises SET demo_slug = 'Bodyweight_Squat' WHERE id = 'ex_bw_squat';
UPDATE exercises SET demo_slug = 'Cable_Crossover' WHERE id = 'ex_cable_crossover';
UPDATE exercises SET demo_slug = 'Cable_Crunch' WHERE id = 'ex_cable_crunch';
UPDATE exercises SET demo_slug = 'Cable_Hammer_Curls_-_Rope_Attachment' WHERE id = 'ex_cable_curl';
UPDATE exercises SET demo_slug = 'One-Legged_Cable_Kickback' WHERE id = 'ex_cable_kickback';
UPDATE exercises SET demo_slug = 'Cable_Seated_Lateral_Raise' WHERE id = 'ex_cable_lateral_raise';
UPDATE exercises SET demo_slug = 'Cable_Rear_Delt_Fly' WHERE id = 'ex_cable_rear_delt_fly';
UPDATE exercises SET demo_slug = 'Cable_Shrugs' WHERE id = 'ex_cable_shrug';
UPDATE exercises SET demo_slug = 'Calf_Press' WHERE id = 'ex_calf_press';
UPDATE exercises SET demo_slug = 'Cat_Stretch' WHERE id = 'ex_cat_cow';
UPDATE exercises SET demo_slug = 'Close-Grip_Barbell_Bench_Press' WHERE id = 'ex_cgbp';
UPDATE exercises SET demo_slug = 'Chin-Up' WHERE id = 'ex_chinup';
UPDATE exercises SET demo_slug = 'Close-Grip_Front_Lat_Pulldown' WHERE id = 'ex_close_pulldown';
UPDATE exercises SET demo_slug = 'Concentration_Curls' WHERE id = 'ex_concentration_curl';
UPDATE exercises SET demo_slug = 'Crunches' WHERE id = 'ex_crunch';
UPDATE exercises SET demo_slug = 'Standing_Dumbbell_Calf_Raise' WHERE id = 'ex_db_calf_raise';
UPDATE exercises SET demo_slug = 'Dumbbell_Bicep_Curl' WHERE id = 'ex_db_curl';
UPDATE exercises SET demo_slug = 'Dumbbell_Flyes' WHERE id = 'ex_db_fly';
UPDATE exercises SET demo_slug = 'Dumbbell_Lunges' WHERE id = 'ex_db_lunge';
UPDATE exercises SET demo_slug = 'Standing_Dumbbell_Press' WHERE id = 'ex_db_ohp';
UPDATE exercises SET demo_slug = 'Standing_Dumbbell_Triceps_Extension' WHERE id = 'ex_db_overhead_ext';
UPDATE exercises SET demo_slug = 'Dumbbell_Bench_Press' WHERE id = 'ex_db_press';
UPDATE exercises SET demo_slug = 'Straight-Arm_Dumbbell_Pullover' WHERE id = 'ex_db_pullover';
UPDATE exercises SET demo_slug = 'Stiff-Legged_Dumbbell_Deadlift' WHERE id = 'ex_db_rdl';
UPDATE exercises SET demo_slug = 'Dumbbell_Rear_Lunge' WHERE id = 'ex_db_reverse_lunge';
UPDATE exercises SET demo_slug = 'Bent_Over_Two-Dumbbell_Row' WHERE id = 'ex_db_row_two';
UPDATE exercises SET demo_slug = 'Dumbbell_Shrug' WHERE id = 'ex_db_shrug';
UPDATE exercises SET demo_slug = 'Split_Squat_with_Dumbbells' WHERE id = 'ex_db_split_squat';
UPDATE exercises SET demo_slug = 'Dumbbell_Squat' WHERE id = 'ex_db_squat';
UPDATE exercises SET demo_slug = 'Dumbbell_Step_Ups' WHERE id = 'ex_db_step_up';
UPDATE exercises SET demo_slug = 'Dead_Bug' WHERE id = 'ex_dead_bug';
UPDATE exercises SET demo_slug = 'Barbell_Deadlift' WHERE id = 'ex_deadlift';
UPDATE exercises SET demo_slug = 'Decline_Barbell_Bench_Press' WHERE id = 'ex_decline_bench';
UPDATE exercises SET demo_slug = 'Decline_Dumbbell_Bench_Press' WHERE id = 'ex_decline_db_press';
UPDATE exercises SET demo_slug = 'Decline_Push-Up' WHERE id = 'ex_decline_pushup';
UPDATE exercises SET demo_slug = 'Deficit_Deadlift' WHERE id = 'ex_deficit_dl';
UPDATE exercises SET demo_slug = 'Dips_-_Triceps_Version' WHERE id = 'ex_dips';
UPDATE exercises SET demo_slug = 'EZ-Bar_Curl' WHERE id = 'ex_ez_curl';
UPDATE exercises SET demo_slug = 'Face_Pull' WHERE id = 'ex_face_pull';
UPDATE exercises SET demo_slug = 'Push-Ups_With_Feet_Elevated' WHERE id = 'ex_feet_elevated_pushup';
UPDATE exercises SET demo_slug = 'Front_Dumbbell_Raise' WHERE id = 'ex_front_raise';
UPDATE exercises SET demo_slug = 'Front_Squat_Clean_Grip' WHERE id = 'ex_front_squat';
UPDATE exercises SET demo_slug = 'Glute_Ham_Raise' WHERE id = 'ex_ghr';
UPDATE exercises SET demo_slug = 'Barbell_Glute_Bridge' WHERE id = 'ex_glute_bridge';
UPDATE exercises SET demo_slug = 'Glute_Kickback' WHERE id = 'ex_glute_kickback';
UPDATE exercises SET demo_slug = 'Goblet_Squat' WHERE id = 'ex_goblet_squat';
UPDATE exercises SET demo_slug = 'Good_Morning' WHERE id = 'ex_good_morning';
UPDATE exercises SET demo_slug = 'Hack_Squat' WHERE id = 'ex_hack_squat';
UPDATE exercises SET demo_slug = 'Hammer_Curls' WHERE id = 'ex_hammer_curl';
UPDATE exercises SET demo_slug = 'Hanging_Leg_Raise' WHERE id = 'ex_hanging_leg_raise';
UPDATE exercises SET demo_slug = 'Barbell_Hip_Thrust' WHERE id = 'ex_hip_thrust';
UPDATE exercises SET demo_slug = 'Handstand_Push-Ups' WHERE id = 'ex_hspu';
UPDATE exercises SET demo_slug = 'Barbell_Incline_Bench_Press_-_Medium_Grip' WHERE id = 'ex_incline_bench';
UPDATE exercises SET demo_slug = 'Incline_Dumbbell_Curl' WHERE id = 'ex_incline_db_curl';
UPDATE exercises SET demo_slug = 'Incline_Dumbbell_Flyes' WHERE id = 'ex_incline_db_fly';
UPDATE exercises SET demo_slug = 'Incline_Dumbbell_Press' WHERE id = 'ex_incline_db_press';
UPDATE exercises SET demo_slug = 'Incline_Push-Up' WHERE id = 'ex_incline_pushup';
UPDATE exercises SET demo_slug = 'Inverted_Row' WHERE id = 'ex_inverted_row';
UPDATE exercises SET demo_slug = 'Wide-Grip_Lat_Pulldown' WHERE id = 'ex_lat_pulldown';
UPDATE exercises SET demo_slug = 'Side_Lateral_Raise' WHERE id = 'ex_lateral_raise';
UPDATE exercises SET demo_slug = 'Leg_Extensions' WHERE id = 'ex_leg_extension';
UPDATE exercises SET demo_slug = 'Leg_Press' WHERE id = 'ex_leg_press';
UPDATE exercises SET demo_slug = 'Low_Cable_Crossover' WHERE id = 'ex_low_cable_crossover';
UPDATE exercises SET demo_slug = 'Lying_Leg_Curls' WHERE id = 'ex_lying_leg_curl';
UPDATE exercises SET demo_slug = 'Machine_Bench_Press' WHERE id = 'ex_machine_chest_press';
UPDATE exercises SET demo_slug = 'Dip_Machine' WHERE id = 'ex_machine_dip';
UPDATE exercises SET demo_slug = 'Leverage_Incline_Chest_Press' WHERE id = 'ex_machine_incline_press';
UPDATE exercises SET demo_slug = 'Reverse_Machine_Flyes' WHERE id = 'ex_machine_reverse_fly';
UPDATE exercises SET demo_slug = 'Machine_Shoulder_Military_Press' WHERE id = 'ex_machine_shoulder_press';
UPDATE exercises SET demo_slug = 'Machine_Triceps_Extension' WHERE id = 'ex_machine_tricep_ext';
UPDATE exercises SET demo_slug = 'V-Bar_Pullup' WHERE id = 'ex_neutral_pullup';
UPDATE exercises SET demo_slug = 'Standing_Military_Press' WHERE id = 'ex_ohp';
UPDATE exercises SET demo_slug = 'Overhead_Squat' WHERE id = 'ex_ohs';
UPDATE exercises SET demo_slug = 'One-Arm_Dumbbell_Row' WHERE id = 'ex_one_arm_db_row';
UPDATE exercises SET demo_slug = 'Cable_Rope_Overhead_Triceps_Extension' WHERE id = 'ex_overhead_tricep_ext';
UPDATE exercises SET demo_slug = 'Pallof_Press' WHERE id = 'ex_pallof_press';
UPDATE exercises SET demo_slug = 'Plank' WHERE id = 'ex_plank';
UPDATE exercises SET demo_slug = 'Preacher_Curl' WHERE id = 'ex_preacher_curl';
UPDATE exercises SET demo_slug = 'Pull_Through' WHERE id = 'ex_pull_through';
UPDATE exercises SET demo_slug = 'Pullups' WHERE id = 'ex_pullup';
UPDATE exercises SET demo_slug = 'Push_Press' WHERE id = 'ex_push_press';
UPDATE exercises SET demo_slug = 'Pushups' WHERE id = 'ex_pushup';
UPDATE exercises SET demo_slug = 'Rack_Pulls' WHERE id = 'ex_rack_pull';
UPDATE exercises SET demo_slug = 'Romanian_Deadlift' WHERE id = 'ex_rdl';
UPDATE exercises SET demo_slug = 'Reverse_Crunch' WHERE id = 'ex_reverse_crunch';
UPDATE exercises SET demo_slug = 'Reverse_Barbell_Curl' WHERE id = 'ex_reverse_curl';
UPDATE exercises SET demo_slug = 'Reverse_Flyes' WHERE id = 'ex_reverse_fly';
UPDATE exercises SET demo_slug = 'Reverse_Grip_Bent-Over_Rows' WHERE id = 'ex_reverse_grip_row';
UPDATE exercises SET demo_slug = 'Seated_Palms-Down_Barbell_Wrist_Curl' WHERE id = 'ex_reverse_wrist_curl';
UPDATE exercises SET demo_slug = 'Triceps_Pushdown_-_Rope_Attachment' WHERE id = 'ex_rope_pushdown';
UPDATE exercises SET demo_slug = 'Russian_Twist' WHERE id = 'ex_russian_twist';
UPDATE exercises SET demo_slug = 'Seated_Barbell_Military_Press' WHERE id = 'ex_seated_bb_press';
UPDATE exercises SET demo_slug = 'Seated_Cable_Rows' WHERE id = 'ex_seated_cable_row';
UPDATE exercises SET demo_slug = 'Seated_Calf_Raise' WHERE id = 'ex_seated_calf_raise';
UPDATE exercises SET demo_slug = 'Seated_Dumbbell_Press' WHERE id = 'ex_seated_db_press';
UPDATE exercises SET demo_slug = 'Seated_Leg_Curl' WHERE id = 'ex_seated_leg_curl';
UPDATE exercises SET demo_slug = 'Side_Bridge' WHERE id = 'ex_side_plank';
UPDATE exercises SET demo_slug = 'Sit-Up' WHERE id = 'ex_situp';
UPDATE exercises SET demo_slug = 'EZ-Bar_Skullcrusher' WHERE id = 'ex_skullcrusher';
UPDATE exercises SET demo_slug = 'Single_Leg_Glute_Bridge' WHERE id = 'ex_sl_glute_bridge';
UPDATE exercises SET demo_slug = 'Smith_Machine_Bent_Over_Row' WHERE id = 'ex_smith_row';
UPDATE exercises SET demo_slug = 'Spider_Curl' WHERE id = 'ex_spider_curl';
UPDATE exercises SET demo_slug = 'Standing_Calf_Raises' WHERE id = 'ex_standing_calf_raise';
UPDATE exercises SET demo_slug = 'Standing_Leg_Curl' WHERE id = 'ex_standing_leg_curl';
UPDATE exercises SET demo_slug = 'Stiff-Legged_Barbell_Deadlift' WHERE id = 'ex_stiff_leg_dl';
UPDATE exercises SET demo_slug = 'Straight-Arm_Pulldown' WHERE id = 'ex_straight_arm_pulldown';
UPDATE exercises SET demo_slug = 'Sumo_Deadlift' WHERE id = 'ex_sumo_dl';
UPDATE exercises SET demo_slug = 'T-Bar_Row_with_Handle' WHERE id = 'ex_tbar_row';
UPDATE exercises SET demo_slug = 'Tricep_Dumbbell_Kickback' WHERE id = 'ex_tricep_kickback';
UPDATE exercises SET demo_slug = 'Triceps_Pushdown' WHERE id = 'ex_tricep_pushdown';
UPDATE exercises SET demo_slug = 'Upright_Barbell_Row' WHERE id = 'ex_upright_row';
UPDATE exercises SET demo_slug = 'Wide-Grip_Lat_Pulldown' WHERE id = 'ex_wide_pulldown';
UPDATE exercises SET demo_slug = 'Standing_Cable_Wood_Chop' WHERE id = 'ex_woodchop';
UPDATE exercises SET demo_slug = 'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench' WHERE id = 'ex_wrist_curl';
