import { styles } from './styles.mjs';

export function homePage() {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Très Fort — Strength training with a plan</title>
<meta name="description" content="Plan your strength training with Claude, then follow it set by set on iPhone. Très Fort brings your workouts and the rest of your training together.">
<meta name="theme-color" content="#0a0a0b"><link rel="icon" href="/assets/app-icon.png"><link rel="apple-touch-icon" href="/assets/app-icon.png">
<style>${styles}</style></head><body>
<a class="skip" href="#main">Skip to content</a>
<header><nav class="wrap" aria-label="Main navigation"><a class="brand" href="/" aria-label="Très Fort home"><img src="/assets/app-icon.png" width="44" height="44" alt=""><span class="wordmark">TRÈS FORT</span></a><div class="nav-links"><a class="app-nav" href="#app">The app</a><a href="/privacy">Privacy</a><a href="#contact">Contact <span aria-hidden="true">↗</span></a></div></nav></header>
<main id="main" class="wrap">
<section class="hero" aria-labelledby="hero-title"><div><p class="eyebrow">Strength training / iPhone</p><h1 id="hero-title">LIFT WITH<span>A PLAN.</span></h1><p class="intro">Plan your strength training with your own AI coach. Follow it set by set on iPhone. Keep the rest of your training in the picture.</p><div class="actions"><button class="button" type="button" disabled>Coming soon on iPhone</button><a class="text-link" href="#app">Explore the app <span aria-hidden="true">↓</span></a></div><p class="status">Public downloads aren’t available yet.</p></div>
<figure class="hero-art"><img class="app-screen" src="/assets/workout.png" width="1206" height="2622" alt="Très Fort’s workout screen, showing a barbell squat prescription and the controls to log a set."><figcaption class="mono">THE PLAN. THE NEXT SET. YOU.</figcaption></figure></section>
<section id="app" class="section-rule" aria-labelledby="app-title"><div class="section-title"><p class="eyebrow">01 / How you train</p><h2 id="app-title">A CONVERSATION.<br>A PLAN. A WORKOUT.</h2></div><div class="feature-grid"><article class="feature"><p class="mono">01</p><h3>Make the plan yours.</h3><p>Build reusable workouts yourself, or connect your own AI app to help shape your routine around your goals, equipment, and training history.</p></article><article class="feature"><p class="mono">02</p><h3>Focus on the next set.</h3><p>Your exercises, reps, weights, and rest timers are there when you need them. Log your work without losing your place.</p></article><article class="feature"><p class="mono">03</p><h3>Keep learning from it.</h3><p>Review your workout history and share feedback with your coach. Adjust the plan as your training and your schedule change.</p></article></div></section>
<section class="product-detail section-rule" aria-labelledby="context-title"><figure><img class="app-screen" src="/assets/library.png" width="1206" height="2622" loading="lazy" alt="The workout library in Très Fort, with reusable Gym and Hotel workouts."><figcaption>App screenshots use sample workout data.</figcaption></figure><div><p class="eyebrow">02 / The bigger picture</p><h2 id="context-title">LIFTING DOESN’T<br>HAPPEN ALONE.</h2><p>Runs, rides, and other workouts affect how you train. Optional Apple Health and Intervals.icu connections bring activity summaries into Très Fort so your coach can consider more than your last lifting session.</p><p>Keep a workout library for the gym, home, or travel. Choose the workout that fits the day, and train alongside friends in private groups.</p><div class="integrations" aria-label="Optional connections"><span>Your AI coach</span><span>Apple Health</span><span>Intervals.icu</span></div><p class="mono">You choose which services to connect.</p></div></section>
<section id="contact" class="contact section-rule" aria-labelledby="contact-title"><div><p class="eyebrow">03 / Get in touch</p><h2 id="contact-title">LET’S TALK TRAINING.</h2><p>Très Fort is developed and operated by Nicholas Marks. For questions or support, get in touch directly.</p><a class="email" href="mailto:nick@tresfort.app">nick@tresfort.app <span aria-hidden="true">↗</span></a></div><div class="privacy-note"><h3>Your training is personal.</h3><p>Learn what Très Fort stores, what connected services and group members can see, and how to export or delete your account.</p><a href="/privacy">Read the privacy policy <span aria-hidden="true">↗</span></a></div></section>
</main><footer><div class="wrap footer-inner"><p>© 2026 Nicholas Marks · Très Fort</p><a href="/privacy">Privacy policy</a></div></footer></body></html>`;
}
