// One policy for the public website and the app's existing /privacy route.
// Keep factual disclosures aligned with the source references in README.md.
export function privacyPage({ appHost = false } = {}) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Très Fort — Privacy Policy</title><meta name="description" content="How Très Fort handles your account, training history, optional Apple Health and Intervals.icu connections, AI coaching access, and account deletion.">
<meta name="theme-color" content="#0a0a0b"><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0a0a0b;color:#f4f4f5;font:1.0625rem/1.75 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}a{color:#f59e0b;text-underline-offset:.25em}a:hover{color:#ffc45b}a:focus-visible{outline:3px solid #f59e0b;outline-offset:5px}header,footer{border-bottom:1px solid #343439;padding:1.5rem max(1.25rem,calc((100% - 1100px)/2))}header a{font-size:1.15rem;font-weight:750;letter-spacing:.06em;text-decoration:none}main{max-width:780px;margin:auto;padding:4rem 1.25rem}h1{font-size:clamp(2.5rem,8vw,4rem);line-height:1.1;margin:.7rem 0 1.2rem;letter-spacing:-.04em}h2{font-size:1.5rem;line-height:1.3;margin:2.7rem 0 1rem}h3{font-size:1.125rem;margin:1.7rem 0 .6rem}p{margin:0 0 1.2rem}li{margin:.65rem 0}ul{padding-left:1.3rem}.meta{color:#b0b0b9;font-size:.9375rem}.eyebrow{font:.875rem/1.6 ui-monospace,monospace;color:#f59e0b;letter-spacing:.08em;text-transform:uppercase}.summary{border-left:3px solid #f59e0b;background:#141417;padding:1.2rem 1.4rem;margin:2rem 0}.summary p:last-child{margin:0}nav{padding:1.2rem 0;border-block:1px solid #343439}nav ul{display:flex;flex-wrap:wrap;gap:.5rem 1.5rem;list-style:none;margin:0;padding:0;font-size:.9375rem}nav li{margin:0}footer{border-top:1px solid #343439;border-bottom:0;font-size:.875rem;color:#b0b0b9}footer p{margin:0}a{overflow-wrap:anywhere}.skip{position:absolute;left:1rem;top:-100px;background:#0a0a0b;padding:1rem}.skip:focus{top:1rem}
</style></head><body><a class="skip" href="#main">Skip to policy</a><header><a href="${appHost ? 'https://tresfort.app/' : '/'}">TRÈS FORT <span aria-hidden="true">↗</span></a></header>
<main id="main"><p class="eyebrow">Your training. Your information.</p><h1>Privacy policy</h1><p class="meta">Très Fort for iPhone and its website · Last updated September 12, 2026</p>
<p>Très Fort is a strength-training app developed and operated by Nicholas Marks. This policy explains what information the app and website handle, why it is used, who can access it, and your choices. For privacy questions or requests, email <a href="mailto:nick@tresfort.app">nick@tresfort.app</a>.</p>
<div class="summary"><p><strong>The essentials:</strong> Très Fort stores your training so you can follow and adapt your plan. Apple Health, Intervals.icu, and AI coaching are optional connections. Group membership shares some workout information; Apple Health group sharing has a separate setting that is off by default.</p><p>Très Fort does not sell your personal information or use your training or health information for advertising.</p></div>
<nav aria-label="Policy contents"><ul><li><a href="#information">Information collected</a></li><li><a href="#sharing">Use and sharing</a></li><li><a href="#choices">Your choices</a></li><li><a href="#retention">Retention and deletion</a></li><li><a href="#website">Website</a></li></ul></nav>
<section id="information"><h2>Information collected</h2>
<h3>Your account and training</h3><ul><li><strong>Account information:</strong> your Sign in with Apple identifier, email address (which may be an Apple private relay address), and any name or display name you provide. Authentication credentials and connection records are used to protect access to your account.</li><li><strong>Training information:</strong> your routines, exercises, schedules, goals and other planning details you provide; sessions, sets, weights, repetitions, durations, effort and fatigue ratings, notes, activity entries, and plan-change history.</li><li><strong>Groups:</strong> groups you create or join, memberships, invitations, and display names used in those groups.</li><li><strong>Technical information:</strong> identifiers and timestamps needed for syncing, device timezone information, queued changes and cached training information on your device, and aggregate service performance metrics. The app backend is configured not to retain or export detailed request, console or trace logs; providers may still process independent account and security information. Changes made through a coaching connection are recorded in the app’s history and audit records.</li></ul>
<h3>Spoken workout feedback, if you choose it</h3><p>When you choose “Talk about your workout” and grant microphone and speech permissions, Très Fort processes microphone audio using Apple’s on-device speech recognition. The audio stays on your iPhone, is not uploaded, and is discarded after transcription. You can review and edit the text before saving. Only text you choose to save becomes part of your training information; unsaved transcription is not stored or sent to your coach. Saved feedback can be read by your authorized coach and is excluded from group feeds.</p>
<h3>Apple Health, if you connect it</h3><p>With the read permissions you grant through Apple Health, Très Fort reads workout information on your iPhone and uploads workout records to its backend. Depending on the workout and available permissions, records can include the workout identifier, activity type, name, source app, start time and timezone, duration, distance, calories, elevation gain, and average and maximum heart rate. Heart-rate samples are used on the device to calculate workout heart-rate summaries.</p><p>Imported workouts support your training history and can be read by your authorized coach connection. Très Fort does not write workouts or other data to Apple Health.</p>
<h3>Intervals.icu, if you connect it</h3><p>Très Fort stores the athlete identifier and authorization credentials needed for the connection, such as access and refresh tokens or an API key. It imports activity records and calendar events returned by Intervals.icu, including their names, dates, descriptions, durations, distances, training-load and other available activity metrics. Provider response data is also retained alongside imported records to support the integration. Completed strength-session summaries and lifting load can be sent back to Intervals.icu.</p>
<h3>Group safety</h3><p>Blocking records the two account identifiers, time and block status so the accounts stop seeing one another’s shared profiles and activities. The operator can apply reversible group-sharing restrictions with a reason category and audit record. These controls do not delete private training records.</p>
<h3>Support correspondence</h3><p>If you email the operator, the email address, message, and information you choose to include are used to respond and resolve your request. Contact email is handled through iCloud Mail.</p></section>
<section id="sharing"><h2>How information is used and shared</h2><p>Information is used to authenticate you, store and synchronize your training, show workout history and progress, support your chosen integrations, enable group features, and maintain the security and reliability of Très Fort.</p>
<h3>AI apps and coaching connections</h3><p>When you authorize an AI app such as Codex or Claude, that app and its configured model provider can request your training records, notes, imported activities, and group information available to you. The app can also change your training plan and record updates through the connection. This includes imported Apple Health information when you have connected Apple Health. The separate Apple Health group-sharing switch does not control your own coach’s access.</p><p>Coaching conversations happen in the AI app you choose using your own account. Information retrieved through the connection is processed under the terms, privacy policies, and settings of that app and its configured model provider. For Codex, review <a href="https://openai.com/policies/privacy-policy/">OpenAI’s privacy policy</a>; for Claude, review <a href="https://www.anthropic.com/legal/privacy">Anthropic’s privacy policy</a>. If you use another app or model provider, review its policy before connecting. Très Fort cannot determine which model an app uses from the connection alone and does not control how long information already retrieved into AI conversations is retained. Disconnecting all AI apps in Profile stops future access through those connections; it does not erase existing conversations.</p>
<h3>People in your groups</h3><p>When you join a group, other members can see shared workout summaries: your display name, session or workout name, completion details, set counts, selected exercise results, activity titles and notes, and available activity metrics. Private strength-session notes, per-set notes, and perceived-fatigue ratings are not included in the group feed.</p><p>Apple Health workouts are excluded from group feeds and group statistics unless you enable their separate sharing setting. That setting is off by default. Your lifting and Intervals.icu activities are governed by group membership, not by the Apple Health sharing switch. Other members may retain information they have already viewed or copied.</p>
<h3>Service providers and the operator</h3><p>Cloudflare hosts the app backend, database, and exercise-media storage. Apple handles Sign in with Apple and the Health permissions you grant. Intervals.icu and your chosen AI app and model provider receive information through the optional connections described above. AI providers may include OpenAI for Codex, Anthropic for Claude, or another provider you configure. The operator can access information as needed to operate, secure, and support the service.</p><p>These providers may process information in countries outside your country of residence. Data exchanged with the app backend travels over HTTPS. Your device also keeps local account and training state to support the app. No advertising SDK or third-party behavioral analytics is included in the app.</p></section>
<section id="choices"><h2>Your choices and controls</h2><ul><li><strong>Export:</strong> use <strong>Profile → Download account data</strong> to save your profile and training information. The export excludes credentials, access tokens, invite codes, and other members’ private information.</li><li><strong>AI coaching:</strong> use <strong>Profile → Disconnect all AI apps</strong> to revoke your authorized coaching connections. You can also remove the connection and manage past conversations in each AI app. Generating a new connect code does not revoke existing connections.</li><li><strong>Apple Health:</strong> disconnect Apple Health in Très Fort to stop future syncing. You can separately revoke its read permissions in Apple’s Health settings and turn off Apple Health group sharing in Très Fort.</li><li><strong>Intervals.icu:</strong> disconnect the integration to stop future syncing and clear the credentials stored for the connection.</li><li><strong>Groups:</strong> leave a group to end your membership, report concerns from group settings or shared activity details, and block another member. Manage your blocks in <strong>Profile → Group safety</strong>. Shared text uses a limited English objectionable-term filter; it cannot detect every abusive phrase. Reports open an email draft containing reference IDs for you to review and send. Reports are checked daily and actionable abuse is addressed within 24 hours. Blocking also applies to future group information accessed by your coach; it cannot erase earlier views, exports or conversations. Apple Health group sharing can be changed separately.</li><li><strong>Correction or help:</strong> edit supported training records in the app or email <a href="mailto:nick@tresfort.app">nick@tresfort.app</a> for help with access, correction, or deletion requests.</li></ul></section>
<section id="retention"><h2>Retention and account deletion</h2><p>Training history is kept so that you can review it and adapt future training. Disconnecting an integration stops future access or syncing; it does not automatically delete the training information already imported into Très Fort. Removing individual training entries may hide them using deletion markers while retaining underlying records for synchronization and history.</p><p>To delete your account, use <strong>Profile → Delete account</strong> and follow the confirmation and any sign-in prompts. Account deletion removes your profile, plans and plan snapshots, sessions, set logs, imported activities and events, notes, audit records, stored integration credentials, coach authorizations, group memberships, associated blocks and sharing restrictions from the active app database. Shared groups with other members can continue under another member.</p><p>Minimal deletion receipts and, for the operator’s account, a hashed identifier may remain to prevent a deleted account or repeated request from restoring access. Operational logs, provider backups, and support correspondence are separate from the active training database and may persist after active records are deleted. Contact the operator for questions about these records; this policy does not promise an immediate purge from all backups.</p><p>Deleting your Très Fort account does not delete the source workouts in Apple Health or Intervals.icu, information already sent to those providers, or AI conversations. Manage those copies with the respective service. You can also request account-deletion help by emailing <a href="mailto:nick@tresfort.app">nick@tresfort.app</a>.</p></section>
<section id="website"><h2>Visiting this website</h2><p>The website presents information about Très Fort and links to contact email. It does not connect to your training account. Cloudflare provides website hosting and may process normal request information, such as your IP address, browser details, requested pages, and technical logs, to deliver and secure the site. The website does not add advertising trackers, marketing analytics, or a mailing-list form. Clicking the email link opens your email application; information is sent when you choose to send a message.</p></section>
<section><h2>Children</h2><p>Très Fort is not directed at children under 13. The operator does not knowingly collect personal information from children under 13. Contact <a href="mailto:nick@tresfort.app">nick@tresfort.app</a> if you believe a child has provided personal information.</p></section>
<section><h2>Changes and contact</h2><p>The date at the top identifies the latest revision. Changes to features or data handling will be reflected in this policy. Privacy and support requests can be sent to Nicholas Marks at <a href="mailto:nick@tresfort.app">nick@tresfort.app</a>.</p></section>
</main><footer><p>© 2026 Nicholas Marks · Très Fort</p></footer></body></html>`;

}

export const PRIVACY_HTML = privacyPage();
